name: PHP Check

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [5.6, 7.2, 7.4]

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: 'PHP ${{ matrix.php }}'
              uses: overtrue/phplint@master
              with:
                  path: .
                  options: --exclude=*.log
